server.port=${PORT:8151}
    spring.application.name=order-service
    management.endpoints.web.exposure.include=health,info
    management.endpoint.health.probes.enabled=true
    server.error.include-message=always
    spring.datasource.url=${DB_URL:jdbc:h2:mem:orders;DB_CLOSE_DELAY=-1}
spring.datasource.username=${DB_USER:sa}
spring.datasource.password=${DB_PASSWORD:}
spring.sql.init.mode=always

orders.base-url=${ORDER_URL:http://127.0.0.1:8151}
instance.id=${HOSTNAME:local-order-service}
