CREATE TABLE IF NOT EXISTS products(id BIGINT PRIMARY KEY,supplier_id BIGINT,name VARCHAR(120),price DECIMAL(14,2),quantity INT);
INSERT INTO products SELECT 1,11,'SSD 1TB',7900,8 WHERE NOT EXISTS(SELECT 1 FROM products WHERE id=1);
INSERT INTO products SELECT 2,22,'Monitor 27',21900,4 WHERE NOT EXISTS(SELECT 1 FROM products WHERE id=2);
