FROM maven:3.9.9-eclipse-temurin-21 AS build
WORKDIR /source
COPY pom.xml .
COPY src ./src
RUN mvn -B -ntp package dependency:copy-dependencies
FROM eclipse-temurin:21-jre-alpine
WORKDIR /app
COPY --from=build /source/target/classes ./classes
COPY --from=build /source/target/dependency ./lib
ENTRYPOINT ["java","-Dfile.encoding=UTF-8","-cp","classes:lib/*","ru.kashpirev.RSocketDemo"]
CMD ["demo"]
