FROM maven:3.9.9-eclipse-temurin-21 AS build
    WORKDIR /source
    COPY pom.xml .
    COPY src ./src
    RUN mvn -B -ntp -DskipTests package
    FROM eclipse-temurin:21-jdk-alpine
    RUN apk add --no-cache curl
    WORKDIR /app
    COPY --from=build /source/target/app.jar app.jar
    ENTRYPOINT ["java","-Dfile.encoding=UTF-8","-jar","app.jar"]
