server.port=${PORT:8080}
    spring.application.name=supplier-service
    management.endpoints.web.exposure.include=health,info
    management.endpoint.health.probes.enabled=true
    server.error.include-message=always
    spring.datasource.url=${DB_URL:jdbc:h2:mem:supplier;DB_CLOSE_DELAY=-1}
spring.datasource.username=${DB_USER:sa}
spring.datasource.password=${DB_PASSWORD:}
spring.sql.init.mode=always

spring.rabbitmq.host=${BROKER_HOST:localhost}
spring.rabbitmq.username=${BROKER_USER:student}
spring.rabbitmq.password=${BROKER_PASSWORD:local-demo-1123}
spring.rabbitmq.connection-timeout=3000
supplier.base-url=${SUPPLIER_URL:http://supplier:8080}
order.base-url=${ORDER_URL:http://orders:8080}
delivery.base-url=${DELIVERY_URL:http://deliveries:8080}
